services:
  webagent:
    build: .
    container_name: webagent
    restart: unless-stopped
    ports:
      - "8787:8787"
    environment:
      - PORT=8787
      - NODE_ENV=production
    env_file:
      - .env
    shm_size: 2g
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8787/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Límites de recursos para producción
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"

